services:
  - type: web
    name: eureka-server
    env: docker
    dockerContext: ./eureka-server
    dockerfilePath: ./eureka-server/Dockerfile
    healthCheckPath: /actuator/health

  - type: web
    name: doctor-services
    env: docker
    dockerContext: ./doctor-services
    dockerfilePath: ./doctor-services/Dockerfile
    healthCheckPath: /actuator/health

  - type: web
    name: patient-service
    env: docker
    dockerContext: ./patient-service
    dockerfilePath: ./patient-service/Dockerfile
    healthCheckPath: /actuator/health

  - type: web
    name: booking-service
    env: docker
    dockerContext: ./booking-service
    dockerfilePath: ./booking-service/Dockerfile
    healthCheckPath: /actuator/health

  - type: web
    name: payment-service
    env: docker
    dockerContext: ./payment-service
    dockerfilePath: ./payment-service/Dockerfile
    healthCheckPath: /actuator/health
